Reforged + ShockAhPI + PlayerAPI
BetterThanUpdates/apron pull request #26
Opened 2022-06-25 00:01 UTC by arthurbambou

2022-06-25 06:58 UTC, halotroop2288 requested changes
I'm not reviewing 179 file changes of bad copy and pasting any further than this.

- You removed stuff that was public.
- You gave things less helpful names.
- You replaced calls to `Logger` with calls to `System.out`

All of this was clearly caused by overwriting whole files with stuff from Reforged without considering the side effects. I'm sorry but I can't accept this in its current state whatsoever.

2022-06-25 14:44 UTC, halotroop2288 requested changes

2022-06-26 22:27 UTC, halotroop2288 approved these changes
lgtm (I'm bored and don't want to check.)

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/apron/ApronPostRemappingVisitor.java
> +											break;
TODO: Replace this section with custom values in mod metadata:
```json
"apron": {
  "classes": {
    "...": "..."
  },
  "reflection": {
    "mod_ClassName": {
      "requestedMember": "returnedMember"
    }
  }
}
```

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/apron/api/ApronApi.java
> +	static Logger getLogger(String name) {
Put this in `Apron` instead of `ApronAPI`

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/block/ForgeBlock.java
> -	int getLightValue(BlockView blockView, int x, int y, int z);
put this back

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/mixin/LadderBlockMixin.java
> -	/**
Put the javadocs back

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/mixin/client/GameRendererMixin.java
> +	private double shockahpi$modifyReach(double constant) {
why is there a shockahpi patch in the forge package?

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/mixin/client/ParticleManagerMixin.java
> +	private void reforged$method_320(CallbackInfo ci) {
Do we know what this does well enough to map it?

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/mixin/client/TessellatorMixin.java
> +	private static final int TRIVERTS_IN_BUFFER = NATIVE_BUFFER_SIZE / 48 * 6;
🤔 "Trivert" isn't a word.

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/modloader/mixin/FurnaceBlockEntityMixin.java
> +				if (this.cookTime == 200) {
I preferred the single-line version of this, but OK.

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/modloader/mixin/client/GameStartupErrorPanelMixin.java
> -	// TODO(halotroop2288): Rewrite this with only the necessary information... ?
`>:(`

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/SAPIAxeItem.java
> +		extends SAPIToolItem {
Why is this line wrapped?

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/SAPIAxeItem.java
> +	private static Block[] field_1681 = new Block[] {Block.WOOD, Block.BOOKSHELF, Block.LOG, Block.CHEST};
This is concerning, implementation wise, but can you just rename it to `effectedBlocks` or something?

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/SAPIPickaxeItem.java
> +	private static Block[] field_352 = new Block[] {Block.COBBLESTONE, Block.DOUBLE_STONE_SLAB, Block.STONE_SLAB, Block.STONE, Block.SANDSTONE, Block.MOSSY_COBBLESTONE, Block.IRON_ORE, Block.IRON_BLOCK,
Also rename this to `effectedBlocks`.

2022-06-26 22:27 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/SAPIShovelItem.java
> +	private static Block[] field_2088 = new Block[] {Block.GRASS, Block.DIRT, Block.SAND, Block.GRAVEL, Block.SNOW, Block.SNOW_BLOCK, Block.CLAY, Block.FARMLAND};
Rename this too.

2022-06-26 22:28 UTC, halotroop2288 commented
That was supposed to be a request changes ooooops

2022-06-27 20:19 UTC, arthurbambou commented on src/main/java/io/github/betterthanupdates/forge/mixin/client/ParticleManagerMixin.java
> +	private void reforged$method_320(CallbackInfo ci) {
no I don't

2022-06-28 22:28 UTC, halotroop2288 requested changes
Seeing how much you changed in ShockAhPI, I'm going to need you to prove that mods which use it haven't been broken. You are targeting a different version than we were before, now.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/ACPage.java
> -public class AchievementPage {
Bruh. Does remapping work or not?
If it works, do not change this back to the improper name!
If it doesn't then why not? That seems like a problem for you to deal with in MRAPI.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/resources/fabric.mod.json
> +      "ACPage": "shockahpi/ACPage",
> `AchievementPage` -> `ACPage`

This seems like a pointless change to me if remapping with MRAPI does work the way it's supposed to.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/forge/mixin/WorldMixin.java
> +		int i = MathHelper.floor(axisalignedbb.minX);
Uh... bad name.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/modloader/mixin/FurnaceBlockEntityMixin.java
> +	 * @author Risugami and Reforged author
Use multiple `@author` tags.

This was [Kleadron](https://github.com/Meefy777/Reforged/blame/a8d6c716a4ae20ccacf82c9445f98f13b1572a86/forge/minecraft.patch#L2832)'s patch in Reforged. (do check if they actually changed anything though.)

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/playerapi/mixin/client/AbstractClientPlayerEntityMixin.java
> +	public boolean method_1373() {
So this can be mapped to `isLyingDown`, then? Wait, I already did that. Is this on latest mappings? They might need to be published.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/reforged/mixin/ShearsItemMixin.java
> +	 * @author Reforged author
[Kleadron](https://github.com/Meefy777/Reforged/blame/a8d6c716a4ae20ccacf82c9445f98f13b1572a86/forge/minecraft.patch#L1898), again.

And this can easily be made into an `@Inject`.

```java
if (Block.BY_ID[i] instanceof IShearable) {
	stack.applyDamage(1, livingEntity);
}
```

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/reforged/mixin/client/MultiplayerClientInteractionManagerMixin.java
> +	public MultiplayerClientInteractionManagerMixin(Minecraft minecraft) {
Maybe it's just me but I avoid making Mixin constructors public in case someone tries to instantiate it by mistake.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/ShockAhPIAxeItem.java
> +	private static Block[] field_1681 = new Block[] {Block.WOOD, Block.BOOKSHELF, Block.LOG, Block.CHEST};
Rename this to something like `effectedBlocks`, similar to earlier comments.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/ShockAhPIPickaxeItem.java
> +	private static Block[] field_352 = new Block[] {Block.COBBLESTONE, Block.DOUBLE_STONE_SLAB, Block.STONE_SLAB, Block.STONE, Block.SANDSTONE, Block.MOSSY_COBBLESTONE, Block.IRON_ORE, Block.IRON_BLOCK,
Again, something like `effectedBlocks`

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/ShockAhPIShovelItem.java
> +	private static Block[] field_2088 = new Block[] {Block.GRASS, Block.DIRT, Block.SAND, Block.GRAVEL, Block.SNOW, Block.SNOW_BLOCK, Block.CLAY, Block.FARMLAND};
And this one too... `effectedBlocks`

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/shockahpi/item/ShockAhPIShovelItem.java
> +		if (arg == Block.SNOW) {
This doesn't seem right at all... Shouldn't it be checking if the array above contains the supplied block?

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/ToolBase.java
> +		for (Integer blockID : Arrays.asList(5, 17, 18, 25, 47, 53, 54, 58, 63, 64, 65, 66, 68, 69, 81, 84, 85)) {
This hard coding makes my soul hurt.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/ToolBase.java
>  	public static final ToolBase Pickaxe = new ToolBase();
😬 Do these fields have to be `Capital Case`?

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/IInterceptHarvest.java
> +	boolean canIntercept(World arg, PlayerEntity arg2, Loc loc, int i, int j);
Ah yes. Making the param names worse... again.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/IInterceptBlockSet.java
> +	boolean canIntercept(World arg, Loc loc, int i);
pls don't do this

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/FreezeDifficultyScreen.java
> -public class FreezeDifficultyScreen extends Screen {
So we're not allowed to freeze the difficulty anymore?

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/BlockHarvestPower.java
> -	@Override
Everything from here down is completely pointless.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/AnimPulse.java
> -	private final Color color1;
Everything from here down is pointless.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/AnimPulse.java
> +import java.awt.*;
We only use the one import... Pointless change!

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/shockahpi/AnimBase.java
> -		int y;
I thought this micro-optimization was pretty funny. It turns several local variables that are created for the same reason over and over again into just two.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/forge/MinecraftForge.java
> +	public static final Logger LOGGER = Apron.getLogger("Minecraft Forge");
Annotate public stuff that didn't exist in other implementations, like this one, with `@ApiStatus.Internal`

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/playerapi/PlayerBase.java
> +@Legacy
JavaDoc?

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/reforged/ReforgedHooks.java
> +	public static final int revisionVersion = 0;
Change to `revisionVersion = 1`

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/reforged/ReforgedMod.java
> +				MinecraftForge.killMinecraft("mod_Reforged", "Please install Reforged after the ForgeSAPI patch and SAPI!");
Not needed.

2022-06-28 22:28 UTC, halotroop2288 commented on src/main/java/reforged/ReforgedMod.java
> +				MinecraftForge.killMinecraft("mod_Reforged", "PlayerControllers were modified. Please fix your installation!");
Probably not needed?

2022-06-28 22:45 UTC, arthurbambou commented on src/main/java/io/github/betterthanupdates/shockahpi/item/ShockAhPIShovelItem.java
> +		if (arg == Block.SNOW) {
It's checked in the super class from another method.

2022-06-28 22:45 UTC, arthurbambou commented on src/main/java/shockahpi/ToolBase.java
> +		for (Integer blockID : Arrays.asList(5, 17, 18, 25, 47, 53, 54, 58, 63, 64, 65, 66, 68, 69, 81, 84, 85)) {
:pensive:

2022-06-28 22:46 UTC, arthurbambou commented on src/main/java/shockahpi/ToolBase.java
>  	public static final ToolBase Pickaxe = new ToolBase();
Public api so it's better to avoid.

2022-06-28 22:54 UTC, arthurbambou commented on src/main/java/shockahpi/FreezeDifficultyScreen.java
> -public class FreezeDifficultyScreen extends Screen {
it wasn't even working/implemented in original r8.

2022-06-28 22:57 UTC, arthurbambou commented on src/main/java/shockahpi/AnimPulse.java
> -	private final Color color1;
ugh no.

2022-06-28 23:47 UTC, halotroop2288 requested changes

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/apron/ApronModRemapper.java
> +		if (Apron.getEnvironment() == EnvType.CLIENT) {
TODO: Add this to custom mod metadata

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/modloader/mixin/FurnaceBlockEntityMixin.java
> +			ItemStack itemstack = ((ReforgedSmeltingRecipeRegistry) SmeltingRecipeRegistry.getInstance()).getSmeltingResult(this.inventory[0]);
:weirdchamp:

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/reforged/mixin/ShearsItemMixin.java
> +	 * @reason
Can just say "implement Reforged function"

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/reforged/ReforgedMod.java
> +		try {
Vanilla class testing probably unneeded.

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/shockahpi/AchievementPage.java
> +		int rnd = random.nextInt(1 + y) + y / 2;
Find out what about this fixed the bug, and try to change it back to a switch.

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/shockahpi/AnimPulse.java
> -	@Override
Re-add this annotation

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/shockahpi/AnimShift.java
> -	@Override
Re-add these annotations

2022-06-28 23:47 UTC, halotroop2288 commented on src/main/java/shockahpi/BlockHarvestPower.java
> -	@Override
You were supposed to roll it back not remove it lmao

2022-06-28 23:49 UTC, arthurbambou commented on src/main/java/io/github/betterthanupdates/modloader/mixin/FurnaceBlockEntityMixin.java
> +			ItemStack itemstack = ((ReforgedSmeltingRecipeRegistry) SmeltingRecipeRegistry.getInstance()).getSmeltingResult(this.inventory[0]);
I know right.

2022-06-28 23:53 UTC, arthurbambou commented on src/main/java/shockahpi/AchievementPage.java
> +		int rnd = random.nextInt(1 + y) + y / 2;
Fix comes from usage of `>`, I don't think it's possible to use it with switch sadly

2022-06-29 00:05 UTC, halotroop2288 commented on src/main/java/shockahpi/AchievementPage.java
> +		int rnd = random.nextInt(1 + y) + y / 2;
This could be done, but it would take far more effort than it's worth, so I guess we'll keep the if-else chain. If I were to implement this, though: I'd just pick a random block from the Block.BY_ID array and use its texture.

2022-06-29 00:07 UTC, halotroop2288 approved these changes

2022-06-29 00:36 UTC, merged