GuiAPI
BetterThanUpdates/apron pull request #32
Opened 2022-07-07 00:27 UTC by arthurbambou

2022-07-07 08:15 UTC, halotroop2288 requested changes
Rebase.

2022-07-07 08:15 UTC, halotroop2288 commented on build.gradle
> +		dirs "./libs"
I don't like this idea. Can these libs be removed in favor of a custom implementation? Or at least be found on [some obscure Maven repo](https://mvnrepository.com/artifact/de.matthiasmann.twl/core/1.0.0)?

I already have concerns about using old mod code without permission (I did plan on asking for permission, but it's a little late for that.)
I don't even know the licenses of these libraries.
Apparently TWL has a [crayon license with a notice of license clause](https://github.com/MatthiasMann/twl/blob/master/src/de/matthiasmann/twl/license.txt).

2022-07-07 08:15 UTC, halotroop2288 commented on src/main/java/guiapi/GuiModScreen.java
> +	public void method_130() {
If this overrides something, annotate it. If not, rename / remove it.

2022-07-07 08:15 UTC, halotroop2288 commented on src/main/java/guiapi/GuiModScreen.java
> +public class GuiModScreen extends Screen {
Yucky name. Probably just ModScreen? Same goes for other "Gui" prefixes.

2022-07-07 08:15 UTC, halotroop2288 commented on src/main/java/guiapi/WidgetText.java
> +public class WidgetText extends WidgetSetting implements StringModel {
Prefix -> Suffix (and remap) for all relevant classes. (sorry)

2022-07-07 08:15 UTC, halotroop2288 commented on src/main/resources/fabric.mod.json
> +      "GuiApiHelper": "guiapi/GuiApiHelper",
Don't forget to address my earlier comments here, or you could break functionality.

2022-07-07 08:15 UTC, halotroop2288 commented on src/main/resources/font.fnt
> +  <kernings count="0">
Can't comment on binary files, but you should remove the textures (and remove them from git history). They're vanilla textures, ya silly.

Except `twlGuiThemeIndentedbuttons.png`

2022-07-07 13:28 UTC, arthurbambou commented on build.gradle
> +		dirs "./libs"
The thing is we don't know at all what version of those library is used here. So I extracted the library's classes from GuiAPI jar to be sure to be using the right ones...

2022-07-07 13:29 UTC, thecatcore commented on build.gradle
> +		dirs "./libs"
TWL's website seems to be gone too.

2022-07-09 05:43 UTC, halotroop2288 commented on build.gradle
> +		dirs "./libs"
Have you tried just using the latest version (`-SNAPSHOT`)?

2022-07-09 13:32 UTC, thecatcore commented on src/main/resources/font.fnt
> +  <kernings count="0">
Fixed

2022-07-11 17:44 UTC, halotroop2288 requested changes

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/GuiApiHelper.java
> +		} else {
Check type before casting. Could be overridden.

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/GuiApiHelper.java
> +	private String displayText_;
underscores BAD

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/ModAction.java
> +	protected Method GetMethodRecursively(Object o, String method) {
Move this to Apron's `ReflectionUtils` class.

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/ModScreen.java
> +	public void method_130() {
wtf is this tho

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/WidgetScreen.java
> +public class WidgetScreen extends Widget {
ScreenWidget

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/guiapi/WidgetScreen.java
> +	public Minecraft minecraftInstance;
client

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/java/io/github/betterthanupdates/guiapi/mixin/client/OptionsScreenMixin.java
> +		this.buttons.add(new ButtonWidget(300, this.width / 2 - 100, this.height / 6 + 192, "Global Mod Settings"));
TODO: an API for adding buttons to the menu.

TODO: This string needs to be localized, eventually.

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/resources/font.fnt
> +  <kernings count="0">
gui.png still exists.

2022-07-11 17:44 UTC, halotroop2288 commented on src/main/resources/font.fnt
> +  <kernings count="0">
font/default.png also

2022-07-11 23:08 UTC, arthurbambou commented on src/main/java/guiapi/ModScreen.java
> +	public void method_130() {
idk

2022-07-11 23:10 UTC, arthurbambou commented on src/main/java/guiapi/WidgetScreen.java
> +	public Minecraft minecraftInstance;
public API :/

2022-07-11 23:11 UTC, arthurbambou commented on src/main/resources/font.fnt
> +  <kernings count="0">
if I remove them, the game crash because it can't find them in the same jar as the theme file...

2022-07-11 23:45 UTC, merged